export const SET_COMBUSTION = 'SET_COMBUSTION';
export const SET_EFFICIENCY = 'SET_EFFICIENCY';
export const SET_PROFILE = 'SET_PROFILE';
export const SET_SOOTBLOW = 'SET_SOOTBLOW';
export const SET_USER_GUIDE = 'SET_USER_GUIDE';
export const SET_USER_MANAGEMENT_REDUCER = 'SET_USER_MANAGEMENT_REDUCER';
export const SET_COMBUSTION_TAG_DETAIL_REDUCER =
  'SET_COMBUSTION_TAG_DETAIL_REDUCER';
